if(global.ammo_count>0)
{
    if(global.weapon_ammo<8)
    {
        global.ammo_count-=(8-global.weapon_ammo);
        global.weapon_ammo=8;
    }
    else
    {
        with(obj_display)
        {
            global.message_display=8;
            alarm[0]=1;
        }
    }
}
else
{
    with(obj_display)
    {
        global.message_display=3;
        alarm[0]=1;
    }
}
