switch(room)
{
    case(rm_test_0):
    {
        //spawn doors
        instance_create(224,288,obj_door_jammed_near);
        instance_create(352,288,obj_door_jammed_far);
        instance_create(480,288,obj_door_0);
        //spawn items if they have not been picked up
        break;
    }
    case(rm_test_1):
    {
        instance_create(192,288,obj_door_0);
        break;
    }
    case(rm_playtest_0):
    {
        instance_create(192,288,obj_door_jammed_far);
        instance_create(768,288,obj_door_1);
        instance_create(384,288,obj_door_2);
        break;
    }
    case(rm_playtest_1):
    {
        instance_create(480,288,obj_door_1);
        if(global.array_keys[0]==false)
        {
            instance_create(192,288,obj_key_0);
        }
        break;
    }
    case(rm_playtest_2):
    {
        instance_create(384,288,obj_door_2);
        instance_create(192,288,obj_door_3);
        instance_create(736,288,obj_door_jammed_far);
        instance_create(1120,288,obj_door_4);
        break;
    }
    case(rm_playtest_3):
    {
        instance_create(384,288,obj_door_3);
        if(global.array_ammo[3]==false)
        {
        instance_create(256,288,obj_ammo_3);
        }
        if(global.array_medkits[1]==false)
        {
        instance_create(192,288,obj_medkit_1);
        }
        break;
    }
    case(rm_playtest_4):
    {
        instance_create(448,288,obj_door_4);
        instance_create(160,288,obj_ladder);
        break;
    }
    default:
    {
        break;
    }
}

